### ISSUE TITLE
Focus on input with a window.scroll don't auto open suggestions

### ISSUE THREAD

**Issue by willjosefi** [darrenjennings/vue-autosuggest#100]
- `vue-autosuggest` version: 1.8.1
- `node` version: v8.11.3
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

What you did:
Using @focus with a window.scroll call.
The reason for scroll window, is because i need to put input on top of the page on mobile devices, to helps keyboard to not hide the input and suggestions

What happened:
Window is scrolled to top but the suggestion don't auto open. I need to click again on input to suggestion being showed.

I created codesandbox showing this happening:
https://codesandbox.io/s/o5947nqlp9
Just click on input, window will be scrolled to top, but suggestion will not be showed, you need to click again on input.

**Comment by darrenjennings** [comment]
There is some custom behavior in the latest beta which will help do whatever you need, but doesn't switching the `@focus` event to `@click` or `@mouseup` fix your issue? e.g. https://codesandbox.io/s/qqqzqryq4w

**Comment by willjosefi** [comment]
hmm.. good idea on using @click, didn't think about that option, as i will use only for mobile devices this seems to work for me.

Thanks...

But, can you give me a quick explanation on why this happen?

**Comment by darrenjennings** [comment]
@willjosefi it looks like when you run your function with @focus, `window.scroll(0, findPos(input));` will fire _before_ the click event and prevent it from firing. With `@click` window.scroll does not stop vue-autosuggest click event.
