### ISSUE TITLE
[Question] Hide suggestion list on blur

### ISSUE THREAD

**Issue by behnoodk** [darrenjennings/vue-autosuggest#105]
- `vue-autosuggest` version: 1.8.3
- `node` version: 10.15.3
- `yarn` version: 1.15.2

Relevant code or config

https://jsfiddle.net/bthqsfyz/2/

Problem description:
First thank you for this component. I am not a javascript nor a Vue expert but I did my best to search the repo before filing this issue.
I want to hide the suggest list when `blur` event is fired on the input.  For example as shown in the fiddle I have three inputs, user uses tab key to navigate, autosuggest input gets focus and list is shown, user wants to move on to the next field and presses tab key but the autosuggest list is still shown. I know that pressing the `esc` key will close the list but I don't want to force the user to have to press the `esc` when they're done with the field. I went through the documentation and searched the whole repo but could not find a method to close the suggestion list myself.

Suggested solution:
I still think I am missing something and there should be a method to close the list. for example I can use `blur` event and when it is fired I call the hide/close method.

**Comment by darrenjennings** [comment]
I have added a very helpful property for this in 2.0, which is currently fairly stable:
```bash
npm install vue-autosuggest@2.0.0-beta.7
```

```vue
  <vue-autosuggest 
    ...
    @blur="closed = true"
    @focus="closed = false"
    :should-render-suggestions="(size, loading) => size >= 0 && !loading && !closed">
```

Demonstrated here:
https://jsfiddle.net/darrenjennings/ajv19e0s/38/

**Comment by behnoodk** [comment]
Perfect!
Thank you.

**Comment by ifdotpy** [comment]
> I have added a very helpful property for this in 2.0, which is currently fairly stable:
> 
> ```shell
> npm install vue-autosuggest@2.0.0-beta.7
> ```
> 
> ```
>   <vue-autosuggest 
>     ...
>     @blur="closed = true"
>     @focus="closed = false"
>     :should-render-suggestions="(size, loading) => size >= 0 && !loading && !closed">
> ```
> 
> Demonstrated here:
> https://jsfiddle.net/darrenjennings/ajv19e0s/38/

@darrenjennings, It brokes main functionality. Please, check your example, try to click on any item. It closes dropdown without selecting an item.

**Comment by darrenjennings** [comment]
@ifdotpy yea good catch. If you detect what is being clicked before you close then you can get around it:

https://jsfiddle.net/darrenjennings/ajv19e0s/66/

e.g. 
```js
      onBlur (e) {
        // relatedTarget is null when you click a suggestion
      	if(e.relatedTarget && e.relatedTarget.tagName === 'INPUT') {
      		this.closed = true          
        }
      },
```

**Comment by ifdotpy** [comment]
@darrenjennings Thank you!

**Comment by brandonkelly** [comment]
@darrenjennings Is there a way to solve this from v1? (This is for a platform where updating to v2 would be a breaking change, so has to wait until the next major release.)

**Comment by darrenjennings** [comment]
@brandonkelly this should be possible just as well by resetting the suggestions to empty. Here's an example with 1.8.1 (the version craftcms is currently using).

codesandbox.io/s/18x-close-on-blur-ldyeu

In case that link eventually expires... The gist of the fix is to reset the suggestions on focus and clear them on blur:
```vue
<vue-autosuggest
      :suggestions="autoSuggestions"
      :input-props="{onInputChange, autocomplete: 'off', id:'autosuggest__input', placeholder:'Do you feel lucky, punk?'}"
      @selected="selectHandler"
      @blur="onBlur"
      @focus="suggestionData = db.getCharacters()"
    >
      <template slot-scope="{suggestion}">
        <span class="my-suggestion-item">{{suggestion.item}}</span>
      </template>
    </vue-autosuggest>
```

```js
import { VueAutosuggest } from "vue-autosuggest";
const db = {
  getCharacters: () => [
    "Frodo",
    "Samwise",
    "Gandalf",
    "Galadriel",
    "Faramir",
    "Éowyn"
  ]
};
export default {
  name: "HelloWorld",

  components: {
    VueAutosuggest
  },
  data: function() {
    return {
      db,
      query: "",
      selected: null,
      suggestionData: []
    };
  },
  computed: {
    autoSuggestions() {
      return [
        { data: this.suggestionData.filter(s => s.indexOf(this.query) > -1) }
      ];
    }
  },
  methods: {
    onBlur(e) {
      if (e.relatedTarget && e.relatedTarget.tagName === "INPUT") {
        this.suggestionData = [];
      }
    },
    onInputChange(e) {
      this.query = e;
    },
    selectHandler(e) {
      this.selected = e;
    }
  }
};
```

**Comment by brandonkelly** [comment]
Worked perfectly, thanks so much @darrenjennings!
