### ISSUE TITLE
If I click in the input field still no results are to be indicated. Only when I have entered the first letter. 

### ISSUE THREAD

**Issue by DieterDeutsch** [darrenjennings/vue-autosuggest#107]
This is a great script, but I have a problem with unfolding the results. If I click in the input field still no results are to be indicated. Only when I have entered the first letter. I tried your script with the Algolia <ais-autocomplete>.
Many thanks for the help
lg
Dieter

**Comment by darrenjennings** [comment]
Try 2.0 beta which might be a little easier.

```bash
npm install vue-autosuggest@2.0.0-beta.7
```

Working example here:
https://codesandbox.io/s/2vr87nyvkp

You should be able to open the suggestions on click in 1.x simply by populating your `:suggestions` on the `@click` event instead of when typing.

**Comment by DieterDeutsch** [comment]
Thanks for the quick help. Such a result as with your demo link I have. This works great with your script. But I do not want that when I click in the input field to load the select field. Only when I have entered the first letter, then load the select field.
Yours sincerely
Dieter

**Comment by darrenjennings** [comment]
The same rule applies, that only when you populate the :suggestions does the component show the results. In the beta version you can see that i have a should-render-suggestions prop. You can see an example of that here:

https://codesandbox.io/s/7z7p8mx2y1

**Comment by DieterDeutsch** [comment]
Ok, great thanks. I'll take a look. 
Greetings Dieter
