### ISSUE TITLE
[Feature request] add componentAttrClassesAutosuggest

### ISSUE THREAD

**Issue by FibreFoX** [darrenjennings/vue-autosuggest#114]
**Problem description:**

Current implementation can take a custom ID, but lacks the ability to take a custom CSS class.

https://github.com/darrenjennings/vue-autosuggest/blob/242dd4dee084d5f6133c09b88da7f9e87f7502be/src/Autosuggest.vue#L2

**Suggested solution:**

Please add the ability to add a CSS-class too. This is needed to be able to add some `position: relative` style or other positioning styles.

**Comment by darrenjennings** [comment]
This is already a capability of the component just add a class to the component and it will pass through. `id` is special since we use it for Aria attributes.

```vue
<vue-autosuggest class="your-class" ...>
```

**Comment by FibreFoX** [comment]
Thanks a lot, it works like a charm ;) I'm new to VueJS, so thanks for that useful hint.
