### ISSUE TITLE
[Issue] The <mark> tag doesn't seem to show up when typing in the search

### ISSUE THREAD

**Issue by jason-beach** [darrenjennings/vue-autosuggest#115]
- `vue-autosuggest` version: 2.0.0

Relevant code or config

https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/autocomplete-results-page

What you did:

I'm noticing that when I update the code base to use vue-autosuggest 2.0.0 from 1.8.3 the highlighting or the <mark/> tag isn't applied so I'm not seeing anything being highlight as we type in the search box. Here's a video to reproduce: https://screencast.com/t/LZ8OFpkHstn

I noticed too there are some changes in the class names which you've documented. You see in the video above that the css for the dropdown looks a bit off when upgrading to vue-autosuggest 2.0.0 but I was able to resolve that.

I'm wondering if I'm not following something here as I was hoping to see a highlight as you type sort of thing happening but I'm not seeing the <mark> tag being wrapped around anything in the ais-highlight component... thanks for this great package!

**Comment by darrenjennings** [comment]
@jason-beach try this demo out for using algolia instant search with `2.0.0` which may guide you in understanding how classes have changed: https://codesandbox.io/s/2vr87nyvkp

More details about what changed here:
https://github.com/darrenjennings/vue-autosuggest/releases/tag/v2.0.0
