### ISSUE TITLE
Turn off suggestions box

### ISSUE THREAD

**Issue by jake-101** [darrenjennings/vue-autosuggest#127]
Is it possible to turn off the suggestions box? I couldn't get my data working with it correctly and made my own outside of the autosuggest component. I still get parent - child node warnings from Dom elements in the suggestions slot though. Great work overall, I probably just need to work with it more but a quick solution for now would be appreciated.

**Comment by darrenjennings** [comment]
Not sure I understand your question. The suggestion box is the whole point of the component so turning it off and rolling your own would just make sense to not use this component? Check out the code sandbox demos to see how it's used with different data inputs

**Comment by jake-101** [comment]
Thanks I probably just need to spend more time with it and look at the actual component.
