### ISSUE TITLE
after-suggestions @click and other click events are invalid

### ISSUE THREAD

**Issue by cdwmhcc** [darrenjennings/vue-autosuggest#128]
- `vue-autosuggest` version: v2.0.0
- `node` version: v10.15.3
- `npm` (or `yarn`) version: v1.16.0

Relevant code or config

``` html
<div slot="after-suggestions">
     <a class="cursor-pointer" @click="alert('success')">more</a>
     <a class="cursor-pointer" @click.native="alert('success')">more</a>
     <a class="cursor-pointer" @click.stop="alert('success')">more</a>
</div>
```

What you did:
I need to add a more button

What happened:
All @click events under slot= "after-suggestions" are invalid

Problem description:

Suggested solution:
Events such as @click can be used normally

**Comment by darrenjennings** [comment]
Can you describe what you mean by "invalid"? You're probably looking for @mouseup.stop. add that to the elements that are being clicked in addition to the click event and lemme know if that helps https://codesandbox.io/s/vueautosuggest-api-clicking-things-in-the-headerfooter-bzdrp

**Comment by cdwmhcc** [comment]
> Can you describe what you mean by "invalid"? You're probably looking for @mouseup.stop. add that to the elements that are being clicked in addition to the click event and lemme know if that helps https://codesandbox.io/s/vueautosuggest-api-clicking-things-in-the-headerfooter-bzdrp
Nice，That's what I need! Thank you very much!
I come from other non-English speaking countries. My English is terrible. I'm sorry!

**Comment by darrenjennings** [comment]
Your english in this instance was just fine actually! Word choice was just a little unclear but grammar was great. Also, issues like these are good because I need to add better docs. Thank you!

**Comment by cdwmhcc** [comment]
> Your english in this instance was just fine actually! Word choice was just a little unclear but grammar was great. Also, issues like these are good because I need to add better docs. Thank you!

Wow, no, no, I should thank you. Thank you for developing and opening up this component. It helped me.
Thank you very much.

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/59967167-05983580-9559-11e9-88f9-4095921c1846.png)
It work!
