### ISSUE TITLE
Expect to add Autocomplete off  to the default config 

### ISSUE THREAD

**Issue by cdwmhcc** [darrenjennings/vue-autosuggest#129]
- `vue-autosuggest` version: 2.0.0
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 1.16.0

#### Relevant code or config

![image](https://user-images.githubusercontent.com/8030134/59967346-39745a80-955b-11e9-9404-623cdd2e96c0.png)

#### What happened:

![image](https://user-images.githubusercontent.com/8030134/59967353-4ee98480-955b-11e9-9107-f80418839394.png)

#### Suggested solution:

The autocomplete attribute is not added by default.
Expect to add it to the default config
And set the default value to off
No manual configuration required

**Comment by darrenjennings** [comment]
ah it seems that it is always "off" to start, but then inputProps are blowing away the defaults sometimes. I see the fix and can push up in a bit.

**Comment by cdwmhcc** [comment]
@darrenjennings 

![image](https://user-images.githubusercontent.com/8030134/59979182-d942ee80-9616-11e9-890b-63927aad25a0.png)

![image](https://user-images.githubusercontent.com/8030134/59979219-4060a300-9617-11e9-8d28-4276048c6b27.png)


I seem to be in a bit of trouble.
The interface returns four items.
But only three items displayed in the components.
I don't know why?

**Comment by darrenjennings** [comment]
@cdwmhcc it's hard to debug your program with limited information but I would be willing to bet you are filtering that list and "webstorm" doesn't have a `p` in it.

**Comment by cdwmhcc** [comment]
> @cdwmhcc很难用有限的信息来调试你的程序，但我愿意打赌你正在过滤那个列表而“webstorm”里面没有`p`。

I need to write you an example.
What time do you rest?

**Comment by cdwmhcc** [comment]
> @cdwmhcc it's hard to debug your program with limited information but I would be willing to bet you are filtering that list and "webstorm" doesn't have a `p` in it.

I need to write you an example.
What time do you rest?

**Comment by darrenjennings** [comment]
Would be great to see a codesandbox reproducing the error. I am in the process of moving across the country, so am unable to determine when I can get to this next, but will keep checking back.

**Comment by cdwmhcc** [comment]
> Would be great to see a codesandbox reproducing the error. I am in the process of moving across the country, so am unable to determine when I can get to this next, but will keep checking back.

https://codesandbox.io/s/codesandbox-nuxt-tnr46?fontsize=14

search key : 'p'

**Comment by darrenjennings** [comment]
Yea if you want to return whatever comes back from the api, don't filter the options by name, just return the data from the response. i.e. instead of returning `filteredOptions` just return `suggestions`

```vue
<vue-autosuggest
  v-model="query"
  :suggestions="suggestions"
```

**Comment by cdwmhcc** [comment]
> Yea if you want to return whatever comes back from the api, don't filter the options by name, just return the data from the response. i.e. instead of returning `filteredOptions` just return `suggestions`
> 
> ```
> <vue-autosuggest
>   v-model="query"
>   :suggestions="suggestions"
> ```

I'm like a fool.
It's amazing that I didn't see it!
