### ISSUE TITLE
event handling i

### ISSUE THREAD

**Issue by FrankIversen** [darrenjennings/vue-autosuggest#132]
- `vue-autosuggest` version: 2.0.1
- `node` version: 10.15.3
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

`<div slot="after-suggestions"> <button v-on:click="redirectMethod">See all products</button></div>`

What you did:
I want to do a redirect when the user hits the button named  "See all products" in the "after-suggestions" slot but something is blocking this from happening. 

What happened:

The method is never hit. I have tried with inline javascript this also does not execute. It seems no event is emitted.

**Comment by darrenjennings** [comment]
@FrankIversen you can accomplish this by using `@mouseup.stop="redirectMethod"`
https://github.com/darrenjennings/vue-autosuggest/issues/75#issuecomment-495055870

**Comment by FrankIversen** [comment]
That did the trick :), Thank you.
