### ISSUE TITLE
@selected event fired when clicking outside drop down

### ISSUE THREAD

**Issue by nickbetsworth** [darrenjennings/vue-autosuggest#135]
### Setup
- `vue-autosuggest` version: 2.0.1
- browser: Chrome

### Steps to re-produce
This issue is present in the [demo](https://darrenjennings.github.io/vue-autosuggest/) and all other usages of the component I've come across.

The following instructions apply to the demo linked above, but similar steps can be taken to reproduce the issue on other implementations.
1. Type character 'e' into the input dialogue.
2. Move the mouse to some area above the input box (this just has to be somewhere outside of the component)
2. Hit the down arrow key twice, such that "Aerin" is highlighted.
3. Optionally move the mouse around outside of the component (just to prove that a mouse move event doesn't resolve this issue)
4. With your mouse still outside the drop-down, click, and you should find that the @selected event is fired for "Aerin".

As a user, I would expect clicking in the area outside of the drop-down to close the dialogue without firing the `@selected` event. I would still expect the `@selected` event to be fired off if the "enter" key is pressed.

### Further issue
The following is another issue I have experienced which is somewhat related, but is not demonstrable in the linked demo.

The issue I have is that the `currentIndex` is never reset to null following a selection. In my implementation I'm removing items as they're selected, and clearing the input field each time.

I have found in conjunction with the first issue mentioned, a user can repeatedly click on the input box, followed by a click outside of the input box, and this will repeatedly add elements until `currentIndex` is out of bounds because I've removed a sufficient number of items.

I would potentially expect the the `currentIndex` to reset if the suggestions are modified.

**Comment by darrenjennings** [comment]
Thanks for the bug reports. I fixed what behavior I think you are describing. Can you test `2.0.2-beta.0` (code in PR #137)  and let me know if it fixes your usage case?

**Comment by nickbetsworth** [comment]
No, thank you for the super swift PR! I've just given it a quick test, and it seems to be working perfectly now. Thanks again!
