### ISSUE TITLE
mismatched suggestions doesn't hide

### ISSUE THREAD

**Issue by kenramirez12** [darrenjennings/vue-autosuggest#138]
- `vue-autosuggest` version: ^2.0.1"
- `node` version: v10.14.2
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript
<vue-autosuggest
        v-model="$v.form.username.$model"
        :suggestions="[clientAccountsList]"
        @selected="selectedAccount"
        :input-props="{placeholder:'Ingrese el correo o usuario'}">  
        <template slot-scope="{suggestion}">
          <span class="my-suggestion-item">{{suggestion.item}}</span>
        </template>
      </vue-autosuggest>
```

What you did:
I'm trying to do a simple autosuggest input for client accounts.

What happened:
It shows the suggestion list correctly but when i write into the input, the missmatched suggestions doesnt hide, i still watching all the suggestions.

Problem description:
I tried with hard code in suggestions prop (just as in documentation), also disabled my custom css.

I also tried copying the css code from the demo site (https://darrenjennings.github.io/vue-autosuggest) but still the same. Hope you can help me.

**Comment by darrenjennings** [comment]
vue-autosuggest is controlled by the `suggestions` prop and you have to filter them yourself. This is because filtering can happen in a naive javascript `.filter` way https://github.com/darrenjennings/vue-autosuggest/blob/master/docs/App.vue#L109 or if you are sending HTTP requests to a backend. If you are filtering in javascript, would recommend having a computed prop that filters based on the v-model input, and if you are sending to a backend, then you will want to fire request on `@input`. Lemme know if that helps.

**Comment by kenramirez12** [comment]
> vue-autosuggest is controlled by the `suggestions` prop and you have to filter them yourself. This is because filtering can happen in a naive javascript `.filter` way https://github.com/darrenjennings/vue-autosuggest/blob/master/docs/App.vue#L109 or if you are sending HTTP requests to a backend. If you are filtering in javascript, would recommend having a computed prop that filters based on the v-model input, and if you are sending to a backend, then you will want to fire request on `@input`. Lemme know if that helps.

Srry! i thought it was done by itself. Thank you so much, it works now.

**Comment by JoshKisb** [comment]
this seems like something that should be in the readme example.

**Comment by darrenjennings** [comment]
@JoshKisb thanks for the note. I updated the README.md codesandbox links to use the latest version.

Check out the latest links and let me know if you run into any issues:
c2f7e88
