### ISSUE TITLE
Working example with nuxtjs

### ISSUE THREAD

**Issue by regenrek** [darrenjennings/vue-autosuggest#140]
2.2.1 - as version:
8.12 - `node` version:
1.1.0 - `npm` (or `yarn`) version:

I tried to implement `vue-autosuggest` with nuxtjs and I run into errors with the base example. 
Is there any example out there which I can adpot?

Demo: https://codesandbox.io/s/codesandbox-nuxt-r6m18

**Comment by darrenjennings** [comment]
Thanks for the reproduction demo link. You are registering the plugin globally, but with the component module, not the plugin module. Don't destructure and it will work:

~import { VueAutosuggest } from "vue-autosuggest";~
import VueAutosuggest from "vue-autosuggest";

**Comment by regenrek** [comment]
Thanks you very much!
