### ISSUE TITLE
Failed to mount component

### ISSUE THREAD

**Issue by YolloDwarf** [darrenjennings/vue-autosuggest#146]
I get a "failed to mount component: template or render function not defined" with the following code:

[..]
<div class="search-form autosuggest-container">
              <vue-autosuggest
                v-model="query"
                :suggestions="[{poiList}]"
                @focus="focusMe"
                @click="clickHandler"
                @input="onInputChange"
                @selected="findPlace"
                :get-suggestion-value="getSuggestionValue"
                :input-props="{id:'autosuggest__input', placeholder:'Search a POI here...'}"
              >
                <div slot-scope="{suggestion}" style="display: flex; align-items: center;">
                  <img :style="{ display: 'flex', width: '25px', height: '25px', borderRadius: '15px', marginRight: '10px'}" :src="suggestion.item.avatar" />
                  <div style="{ display: 'flex', color: 'navyblue'}">{{suggestion.item.name}}</div>
              </div>
              </vue-autosuggest>
            </div>
[..]

<script>
import VueAutosuggest from "vue-autosuggest"

export default {
  name: 'Map',
  components: {
    ...
    'vue-autosuggest': VueAutosuggest,
    ...
  },
  ...
</script>

I basically copied the basic code in the README but the template won't render.

**Comment by darrenjennings** [comment]
You are wanting to import is as a component, but you are importing the plugin. See [usage](https://github.com/darrenjennings/vue-autosuggest#usage):

Load VueAutosuggest into your vue app globally.

```js
import VueAutosuggest from "vue-autosuggest";
Vue.use(VueAutosuggest);
```

or locally inside a component:

```js
import { VueAutosuggest } from 'vue-autosuggest';
export default {
  ...
  components: {
      VueAutosuggest
  }
  ...
};
```
