### ISSUE TITLE
programmatically select suggestion when mounted

### ISSUE THREAD

**Issue by anurat** [darrenjennings/vue-autosuggest#151]
I have a form with autosuggest in it with backend validation. When user submits a request the server will validate and returns to the same form when validation failed. Then I'd like the input selected by user from the previous request to still show.

According to issue #94, there is a way to programmatically select the first suggestion when a user types tab key. I tried to do the same thing inside mounted() method.

```js
tabHandler(){
  const { listeners, setCurrentIndex, setChangeItem, getItemByIndex } = this.$refs.autosuggest

  setCurrentIndex(0)
  setChangeItem(getItemByIndex(this.$refs.autosuggest.currentIndex), true)
  this.$refs.autosuggest.loading = true
  listeners.selected(true)
},
```

But at `getItemByIndex`, I got an error about the reference is not found.
Any suggestions would be appreciated.

**Comment by anurat** [comment]
@darrenjennings It looks like the reference "computed_section_0" hasn't been created  
right after the suggestions value is updated. Therefore an error in `Autosuggest.vue` at `getItemByIndex` method

```js
let childSection = this.$refs["computed_section_" + i][0];
```

Is there anyway I can create the ref immediately?  
Or how can I wait until the the ref is being created?

**Comment by anurat** [comment]
@darrenjennings  
I'm not sure whether you have seen this issue.  
I'd like to know whether solving this problem is possible.  
If it's not then I will just move on.

Thank you and best regards,

**Comment by darrenjennings** [comment]
@anurat can you provide a codesandbox reproduction? You could fork https://codesandbox.io/s/vueautosuggest-api-fetching-wck52 as a starting point

**Comment by anurat** [comment]
Thank you very much @darrenjennings 

Here is my codesandbox 
https://codesandbox.io/s/vueautosuggest-api-fetching-luser

And what I want to do is call `tabHandler` after `fetchResults` have populated the results.

```js
  mounted(){
    this.fetchResults(this.tabHandler)
  },
```

```js
    fetchResults(callback) {
        ...
        Promise.all([photosPromise, usersPromise]).then(values => {
          ...
          photos.length &&
            this.suggestions.push({ name: "hotels", data: photos });

          callback()
        });
      }, this.debounceMilliseconds);
    },
```

**Comment by darrenjennings** [comment]
I'm not sure I get the desired result for you, but if you wrap it in a nextTick, it will do as you want.

```diff
- callback()
+ this.$nextTick(() => this.tabHandler())
```

**Comment by anurat** [comment]
Thank you @darrenjennings 

I tried nextTick as you suggested but still got an error below.
![image](https://user-images.githubusercontent.com/2355534/67631713-3f44c880-f8cc-11e9-9e8d-6632848dbb8d.png)

It's about `this.$refs['computed_section_' +n]` that I mentioned earlier.  
May be a reference still hasn't been created after nextTick?

**Comment by anurat** [comment]
Hi @darrenjennings  
sorry to bother you again.  
What do you think about this problem?  
Do you think that there should be a work around or it is just not possible to fix?

Thanks a lot,

**Comment by darrenjennings** [comment]
@anurat you are fetching and trying to change the item before the results list has been populated. Remove `this.fetchResults` from mounted. Let me know if this helps.

**Comment by darrenjennings** [comment]
@anurat you can control what the query is in v-model from the server, and it's up to you to fetch what is selected. I do something like this at work where user has to click invalid input which will trigger refetch https://codesandbox.io/s/vueautosuggest-151-3yqhs

**Comment by anurat** [comment]
@darrenjennings  
Yes, what I missed was adding v-model to autosuggest.  
This way I don't have to simulate the select item behavior.
Thanks again for your help and thank you for sharing this nice tool.
