### ISSUE TITLE
Re-opening dropdown with same query starts you at the second option

### ISSUE THREAD

**Issue by thegregthomp** [darrenjennings/vue-autosuggest#152]
- `vue-autosuggest` version:2.0.4
- `node` version:10.16
- `npm` (or `yarn`) version:6.9

Relevant code or config

```javascript

```

What you did:
entering input, viewing dropdown, exiting input and re-entering input, if you hit down it starts at the second item in the list and not the first.

What happened:

Reproduction repository:
is possible to see on repo demo: https://darrenjennings.github.io/vue-autosuggest/
also visible on algolia demo under autocomplete example: https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/vue/

Problem description:
re-opening dropdown with the same query starts you at the second item in the list

**Comment by darrenjennings** [comment]
yea good catch. looks like a bug with the hover state, as `aria-activedescendant` shows that the first option is selected, but it's not highlighted. hitting "enter" even selects the first option.
