### ISSUE TITLE
How to right clean input?

### ISSUE THREAD

**Issue by Sendoo** [darrenjennings/vue-autosuggest#156]
- `vue-autosuggest` 2.0.4:
- `node` 12.13.0:
- `npm` (or `yarn`) 6.13.0:

What you did:

I want to create a method by which cleaning input (v-model)
`
selectSection(data) {
      if (data) {
        this.currentSuggestValue = '  ';
      }
    }
`

What happened:

This code cleared input, but not rendering placeholder (empty).

Problem description:

How to right clean input?

**Comment by darrenjennings** [comment]
@Sendoo assuming you have `v-model="currentSuggestionValue'` then any reason you are not simply clearing it all the way? e.g.  

```diff
- this.currentSuggestValue = ' '
+ this.currentSuggestValue = null
```

**Comment by Sendoo** [comment]
> 
> 
> @Sendoo assuming you have `v-model="currentSuggestionValue'` then any reason you are not simply clearing it all the way? e.g.
> 
> ```diff
> - this.currentSuggestValue = ' '
> + this.currentSuggestValue = null
> ```

Since this is a text field, an error will be shown with null.
![изображение](https://user-images.githubusercontent.com/46229254/68678611-eda46b00-0566-11ea-8779-5ee17e68edea.png)

**Comment by Sendoo** [comment]
I deleted props `get-suggestion-value` and the previous cleaning worked as it should!

**Comment by Sendoo** [comment]
I deleted props `get-suggestion-value` and the previous cleaning worked as it should!
