### ISSUE TITLE
Select item by id

### ISSUE THREAD

**Issue by Sendoo** [darrenjennings/vue-autosuggest#157]
- `vue-autosuggest` version: 2.0.4
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 6.13.1

Hi
Tell me, is it possible to select an item from the list, knowing its ID?
I want to pass this parameter on a vue router.

`
{
  {
    id: 1,
    title: Mike,
  },
  {
    id: 2,
    title: Tom
  },
.....
}
`

**Comment by darrenjennings** [comment]
@Sendoo vue-autosuggest doesn't dictate what your objects are. You should be able to lookup on `@selected` event to do as you see fit based on what `:suggestions` are.
