### ISSUE TITLE
this.$el.contains error in onDocumentMouseUp in IE11

### ISSUE THREAD

**Issue by dominikg** [darrenjennings/vue-autosuggest#158]
- `vue-autosuggest` version: 2.0.4

What you did:
Use `<vue-autosuggest>` in a runtime compiled component and open the page in IE11

What happened:
When clicking anywhere in the document a script error occurs because this.$el does not have a method called contains.

Problem description:
This is caused by the fact that this.$el is an empty comment node at the time of invocation which apparently do not have a contains method in IE11. 

Suggested solution:
a simple solution would be to check if 'contains' actually exists before trying to invoke it

**Comment by darrenjennings** [comment]
@dominikg we could document this better, but you need to polyfill this for IE11. Here's a simple one:

```js
Node.prototype.contains = function (el) {
  while (el = el.parentNode) {
    if (el === this) return true
  }

  return false
}
```

**Comment by darrenjennings** [comment]
Leaving it up to users to polyfill. Will add a note in the docs.
