### ISSUE TITLE
How to highlight keywords?

### ISSUE THREAD

**Issue by cdwmhcc** [darrenjennings/vue-autosuggest#159]
How to highlight keywords?

**Comment by darrenjennings** [comment]
Here's a codesandbox that does it: https://codesandbox.io/s/ol7yp20966

something like this:

```vue
<template slot-scope="{ suggestion }">
  <span v-html="bolden(query, suggestion.item.title)"/>
```

```js
bolden (text, suggestion) {
  var regex = new RegExp("(" + text + ")", "gi");
    
  return suggestion.replace(regex, "<b>$1</b>");
}
```

**Comment by cdwmhcc** [comment]
> Here's a codesandbox that does it: https://codesandbox.io/s/ol7yp20966
> 
> something like this:
> 
> ```
> <template slot-scope="{ suggestion }">
>   <span v-html="bolden(query, suggestion.item.title)"/>
> ```
> 
> ```js
> bolden (text, suggestion) {
>   var regex = new RegExp("(" + text + ")", "gi");
>     
>   return suggestion.replace(regex, "<b>$1</b>");
> }
> ```

Wow，Thank you very much，it works! Haha
