### ISSUE TITLE
Is it possible to fetch results without making a query every time?

### ISSUE THREAD

**Issue by simplenotezy** [darrenjennings/vue-autosuggest#169]
I'd like to fetch suggestions on page load, but from an endpoint, so they are not bloating the page. However, I don't want to make a query every time user types something in. Is this possible? I couldn't find it in the examples.

**Comment by darrenjennings** [comment]
Yes, you will only have to pass data to `suggestions` but never change them and don’t fire any XHR events on input. You can control the filtering all on the client.

**Comment by simplenotezy** [comment]
Thanks! Could you come with a short example? Could be could if suggestions would accept a function callback instead of only array.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by darrenjennings** [comment]
@simplenotezy suggestions are just props so if they change, then vue-autosuggest re-renders.

Check out the example from the readme. I added some comments to the `mounted` lifecycle to help explain a bit more:
https://codesandbox.io/s/vueautosuggest-api-data-objects-01p5i

**Comment by simplenotezy** [comment]
Thanks a lot!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
