### ISSUE TITLE
There is no disabled input props

### ISSUE THREAD

**Issue by mhlsf** [darrenjennings/vue-autosuggest#170]
# Problem description:

We should be able to set a disabled state for the input.

# Suggested solution:

Adding a props to toggle disabled state

**Comment by darrenjennings** [comment]
This is already available via: https://github.com/darrenjennings/vue-autosuggest#inputprops

> can add any props to <input> as the component will v-bind inputProps. Similar to rest spread in JSX. See more details here: https://vuejs.org/v2/api/#v-bind. The name attribute is set to "q" by default.

e.g.

```vue
<vue-autosuggest :input-props="{ disabled: true }"
  ...
```
