### ISSUE TITLE
Question - How to force suggestion list to render on input focus

### ISSUE THREAD

**Issue by imt-telliott** [darrenjennings/vue-autosuggest#171]
If this isn't the correct place to ask this type of question, please let me know.

I would like to know the suggested way of forcing the suggestion list to render when the input receives focus via tabbing. Right now, it appears that functionality only occurs when the input is actually clicked.

Thanks!

**Comment by darrenjennings** [comment]
@imt-telliott you can use the `should-render-suggestion` to create a focus state.

Example:
https://codesandbox.io/s/vueautosuggest-171-22l6b

e.g.
```vue
 <vue-autosuggest
  ...
  @focus="isFocused = true"
  @blur="isFocused = false"
  :should-render-suggestions="(size, loading) => (size >= 0 && !loading) || isFocused"
>
```

I like this behavior!

**Comment by imt-telliott** [comment]
Thanks so much for the quick reply, I was looking at the source and it never occurred to me to override this and instead I went the "hacky" way and updated loading to meet my needs. 

This is much better.
