### ISSUE TITLE
How can I use the tab key to select a suggestion?

### ISSUE THREAD

**Issue by canvasandcode** [darrenjennings/vue-autosuggest#172]
Hi,

I've been asked to allow users to use the tab key to select an autosuggestion. Currently, it works fine using the up and down arrow and using the enter key. But for some reason, I have to have the exact same functionality with the tab key. 

My Vue file looks like this:

https://codesandbox.io/s/vueautosuggest-api-fetching-k7pvw

I would greatly appreciate your help and advice on this.

Thanks

**Comment by darrenjennings** [comment]
Looks like that example is missing vue-bootstrap dependency and the restaurant data file isn't there. Either way, this might help you get what you need:

https://codesandbox.io/s/vueautosuggest-172-q96jp

The idea being that you need your own "loading" state variable to tell vue-autosuggest when to render and fire off the onSelected event through a ref (but then clearing the hasTabbed in the click and focus events so that it behaves normally):

```js
tabHandler(e) {
  this.$refs.autosuggest.listeners.selected(true)
  this.hasTabbed = true
}
```

**Comment by canvasandcode** [comment]
Thank you for the quick response - I still couldn't get it to work, I'm
getting the following console error when I try to tab on a suggestion: *Error
in v-on handler: "TypeError: Cannot read property 'listeners' of
undefined" *

Why would this be undefined if my component has the ref "*autosuggest*".

My component looks like this, and I'm using the tabHandler and
selectHandler methods you mentioned:

<vue-autosuggest
v-model="restaurantModel"
ref="autocomplete"
@selected="selectHandler"
@click="animateInputLabel"
@focus="hasTabbed = false"
@keydown.tab.prevent="tabHandler"
:suggestions="suggestions"
:inputProps="inputProps"
:sectionConfigs="sectionConfigs"
:renderSuggestion="renderSuggestion"
:getSuggestionValue="getSuggestionValue"
/>

**Comment by darrenjennings** [comment]
the ref you pasted is called "autocomplete" so you'd need to reference that e.g. `this.$refs.autocomplete.listeners.selected`

**Comment by darrenjennings** [comment]
@canvasandcode did this help?

**Comment by canvasandcode** [comment]
Sorry for the late response, the project was paused due to everything happening :) Thanks for your help!

**Comment by darrenjennings** [comment]
sorry to hear @canvasandcode hope you are well and safe.
