### ISSUE TITLE
HowTo set a value from component parent?

### ISSUE THREAD

**Issue by MuyBien** [darrenjennings/vue-autosuggest#173]
Hi,

I'm trying to use your component but I'm facing a problem: how to set a value from outside the component? The v-model is used for the filter input value...  

Is there a way?

Thanks.

**Comment by darrenjennings** [comment]
not sure exactly what you are asking, but v-model is the value of the in `<input />` so it can be used in the component parent:

```html
  You are searching for {{ query }}
  <vue-autosuggest  v-model="query" ...
```

**Comment by MuyBien** [comment]
Sorry, I forgot how autocomplete works...
I was more looking for a select with options load dynamically.
Thanks for your answer ;)
