### ISSUE TITLE
changing sectionConfigs has unexpected behavior

### ISSUE THREAD

**Issue by darrenjennings** [darrenjennings/vue-autosuggest#176]
When items of my suggestions array change, the before-section-{name} slots disappear

Originally posted here by @diskopete
https://github.com/darrenjennings/vue-autosuggest/issues/139#issuecomment-595107197

Reproducible codesandbox:
https://codesandbox.io/s/vueautosuggest-20-base-6n670

**Comment by DiskoPete** [comment]
🙌 thank you!
