### ISSUE TITLE
[Feature Request] Add autofocus prop

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [darrenjennings/vue-autosuggest#179]
Please, add support for autofocus input behavior on component mounted by adding `autofocus` boolean prop

**Comment by darrenjennings** [comment]
thanks for the feedback @AndrewBogdanovTSS. Closing re: https://github.com/darrenjennings/vue-autosuggest/issues/44#issuecomment-535163310

> In this scenario, it is a native element method .focus, which I think is better left for the user to implement in lieu of vue-autosuggest handling it via prop or otherwise.
