### ISSUE TITLE
Cannot find module './Autosuggest.vue'

### ISSUE THREAD

**Issue by trocho** [darrenjennings/vue-autosuggest#18]
Hi!

I have some problem when try to include with the gulp and the browserify.

```
Error: Cannot find module './Autosuggest.vue' from '/var/www/withpassion/docker-projects/wesele123.local/html/node_modules/vue-autosuggest/dist'
    at /var/www/withpassion/docker-projects/wesele123.local/html/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/withpassion/docker-projects/wesele123.local/html/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/withpassion/docker-projects/wesele123.local/html/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/withpassion/docker-projects/wesele123.local/html/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

Process finished with exit code 1
```

My run code
`import VueAutosuggest from 'vue-autosuggest'`

Any idea?

**Comment by darrenjennings** [comment]
I am seeing the same thing from browserify builds. I've confirmed other vue libraries that are using a similar UMD bundling via webpack as the one I'm using receive the same issue while building via browserify. I'll look into this and report back!

**Comment by darrenjennings** [comment]
@trocho should be fixed with 1.1.0 version. Thanks!

**Comment by trocho** [comment]
I have a some other problem now :)

![zaznaczenie_573](https://user-images.githubusercontent.com/9249585/33568616-59737b28-d927-11e7-9b65-30170d22d41d.png)


```
vue.js:485 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueAutosuggest>
```

**edit**

I'm thinking then this can help
https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by darrenjennings** [comment]
VueAutosuggest is a plugin, so you will need to case `Vue.use()` to load it in your app so it can be used. 

Example:
```js
import Vue from 'vue'
import App from './App.vue'
import VueAutosuggest from 'vue-autosuggest';

Vue.use(VueAutosuggest);

new Vue({ // eslint-disable-line no-new
  el: '#app',
  render: (h) => h(App)
})
```

I'll update the README.md to make this more clear.

**Comment by trocho** [comment]
Yes. Good idea!

Thanks for help
