### ISSUE TITLE
Need eventlisteners for @focus and @blur equivalents

### ISSUE THREAD

**Issue by michaeljakob** [darrenjennings/vue-autosuggest#180]
I see that @focus can be achieved with @selected. However, a @blur event (available on normal <input>) is lacking, isn't it?

**Comment by michaeljakob** [comment]
In fact, @blur and @focus work just as normal. This should be added to the docs :)

**Comment by darrenjennings** [comment]
thanks for the note @michaeljakob added to the docs! https://github.com/darrenjennings/vue-autosuggest#events
