### ISSUE TITLE
Using arrow keys to navigate down and up again lets you select negative / non-existant entries

### ISSUE THREAD

**Issue by account-suspended** [darrenjennings/vue-autosuggest#190]
- `vue-autosuggest` version: 2.1.1
- `node` version: v9.6.1
- `npm` version: 6.0.1

What you did:
1) Go to any implementation, for example: https://darrenjennings.github.io/vue-autosuggest
2) Type a letter so you get the suggestions
3) Use the down arrow key to select a suggestion
4) Use the up arrow key to go back to the input and keep pressing up a couple of times
5) To get back to the suggestions, you'd expect that the down arrow key would work immediately, but you have to press it as often as you pressed the up arrow key in step 4

Tried it in current versions of Chrome, Firefox, Safari on current macos and Windows.

Suggested solution:
Probably make sure the index variable can't be negative

**Comment by darrenjennings** [comment]
seems like a regression, thanks for noticing. Will coerce the index to not exceed negative -1

**Comment by darrenjennings** [comment]
Released in https://github.com/darrenjennings/vue-autosuggest/releases/tag/v2.1.2
