### ISSUE TITLE
Button inside item didn't work as expected.

### ISSUE THREAD

**Issue by HarikiRito** [darrenjennings/vue-autosuggest#196]
- `vue-autosuggest` version: 2.1.2
- `node` version:
- `npm` (or `yarn`) version:

What you did:
Add a button into the list item suggestion

What happened:
Button click doesn't work (Function not call, and suggestions disappear)

Reproduction sandbox/repository:
[Code sandbox](https://codesandbox.io/s/vue-autosuggest-button-inside-1e3hx?file=/src/App.vue)

Suggested solution:
Button click can prevent suggestions from closing and work as expected

**Comment by darrenjennings** [comment]
You can do it via `mouseup.stop` https://github.com/darrenjennings/vue-autosuggest/issues/168#issuecomment-585015240
