### ISSUE TITLE
How to use multiple vue-autosuggest components in the same page

### ISSUE THREAD

**Issue by deandelponte** [darrenjennings/vue-autosuggest#198]
Do you have examples of how to use the latest build to utilize multiple `vue-autosuggest` components on the same page?  I've been unable to find a way to do this in the documentation.

Thanks!

**Comment by darrenjennings** [comment]
It should "just work", but there's a demo on the readme that should give you a working example:
codesandbox.io/s/vueautosuggest-multiple-vue-autosuggests-545ee

**Comment by deandelponte** [comment]
Thank-you for your response

**Comment by jesseschutt** [comment]
Thanks for your work on this component! 

If I'm not mistaken, doesn't multiple instances result in duplicate ids on the page?

**Comment by AdrianBathurst** [comment]
The input field's id generates unique, but the tags surrounding it don't generate unique...

![image](https://user-images.githubusercontent.com/9006517/107217769-91005c00-6a06-11eb-9386-4295bf013f16.png)


![image](https://user-images.githubusercontent.com/9006517/107217784-978ed380-6a06-11eb-85a2-4a44333b2a16.png)

**Comment by jesseschutt** [comment]
Thank you for the explanation @AdrianBathurst 👍
