### ISSUE TITLE
input should be editable

### ISSUE THREAD

**Issue by darrenjennings** [darrenjennings/vue-autosuggest#20]
Currently input is only editable via a ref. Vue-autosuggest uses v-model for searchInput + a watcher. This poses a few problems since the value is not passed from the parent component.

Research best way to handle setting input value without using a ref and implement. This is useful for setting or clearing the input programmatically.

Example:
https://jsfiddle.net/darrenjennings/dtexzqsL/

**Comment by darrenjennings** [comment]
Closing, using refs isn't all that bad.

**Comment by puremana** [comment]
Doesn't work anymore. On version 1.8.3. 

`this.$refs.autosuggest.searchInput = "test";`

Is there another solution other than updating to beta version?
