### ISSUE TITLE
Preselect (initial value) example

### ISSUE THREAD

**Issue by demiro** [darrenjennings/vue-autosuggest#200]
When checking the storybook for examples I found [this one](https://darrenjennings.github.io/vue-autosuggest/storybook/?selectedKind=Vue-Autosuggest&selectedStory=with%20property%3A%20initial%20value&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), that has an initial value...

what it does it only sets the value of the query (in the input box) and does not select (highlight the item from the list).

How do we actually set (and highlight) a initial item (and not just the query text) ?

**Comment by darrenjennings** [comment]
@demiro I need to remove the stories as they haven't been updated in a while. For example, initialValue has been deprecated and now `v-model` is how you should use initial values. does this help you? there is currently no default behavior to trigger a "highlight" after the rendering of the suggestion list.
