### ISSUE TITLE
onDocumentMouseUp

### ISSUE THREAD

**Issue by ggkovacs** [darrenjennings/vue-autosuggest#203]
How can i disable onDocumentMouseUp event inside item?

This example not working:
https://github.com/darrenjennings/vue-autosuggest#suggestion-item-ie-default-slot

Link (a) element trigger onDocumentMouseUp.

**Comment by darrenjennings** [comment]
closing as a duplicate https://github.com/darrenjennings/vue-autosuggest/issues/134
