### ISSUE TITLE
Smart result ordering

### ISSUE THREAD

**Issue by jestrux** [darrenjennings/vue-autosuggest#204]
![Screenshot_20200915-194654_Samsung Internet.jpg](https://user-images.githubusercontent.com/8426172/93240043-4c8ccf00-f78c-11ea-9406-b0559b75b32a.jpg)

Is there a way to make the results appear in order of match index? So like in the screenshot above Samwise Gamgee should appear before the other results because Sam matches at the start.

**Comment by darrenjennings** [comment]
@jestrux vue-autosuggest is just the presentation layer, so for example, that screenshot is just using a simple .filter + indexOf https://github.com/darrenjennings/vue-autosuggest/blob/master/docs/App.vue#L139. If you want "smarter" matches, then you have to defer this work to a search engine (on the server or maybe a naive one in the browser)

**Comment by jestrux** [comment]
Oh okay, makes sense. Really love what you've done with this by the way, I especially love the custom jsx render method.
