### ISSUE TITLE
How to prevent arrows keydown event opening suggest?

### ISSUE THREAD

**Issue by usernamehw** [darrenjennings/vue-autosuggest#209]
- `vue-autosuggest` version: 2.2.0
- `node` version: 14.15.0
- `npm` (or `yarn`) version: 6.14.8

## Problem description:

I need to use `keydown` event for `ArrowDown`/`ArrowUp` and the input is opening the suggestion list when it's not visible.

Only want to use the event when suggestions are not visible. Right now it opens the autocomplete by pressing `ArrowDown` and there seems to be no way of preventing it.

**Comment by darrenjennings** [comment]
@usernamehw can you add a reproduction codesandbox?

**Comment by usernamehw** [comment]
Wrote workarounds with the `shouldRenderSuggestions`. And with the number of workarounds in place it would take too much time to write a minimal sample.
