### ISSUE TITLE
Details on WAI-ARIA compliance

### ISSUE THREAD

**Issue by NateWr** [darrenjennings/vue-autosuggest#24]
Wow, an auto-suggest that's WAI-ARIA compliant! I thought I'd never see one. :+1: 

Have you documented anywhere the particular aspects of your component that make it WAI-ARIA compliant, or any tests you've done with particular screen-reader devices?

I work for a small non-profit on open-source software. We don't have the resources to acquire and test many screen-readers, but it'd be good if I can tell my team what we expect our screen-reader support to be, so that they can communicate it to institutions downstream.

Thanks!

**Comment by darrenjennings** [comment]
@NateWr this is not well documented nor tested on many screen readers. I've mimicked other popular libraries and followed ARIA compliance [here](https://www.w3.org/TR/wai-aria-1.1/#textbox) and have some tests here:
https://github.com/Educents/vue-autosuggest/blob/master/__tests__/autosuggest.test.js#L218

I see a couple of bugs actually doing a quick testing on a web screen reader. I'll get this fixed ASAP. Thanks!

**Comment by darrenjennings** [comment]
Bugs fixed and tests are updated so you can see the more technical side of aria compliance. It looks like I have all the bases covered.

I tested using Vox chrome screen reader and it behaves as expected now. Let me know if you come across any weird behavior on other screen readers. Thanks!

**Comment by NateWr** [comment]
Thanks @darrenjennings that's very helpful!
