### ISSUE TITLE
Ability to turn browser autocomplete off 

### ISSUE THREAD

**Issue by mhimi1** [darrenjennings/vue-autosuggest#28]
- `vue-autosuggest` version: 1.1.1
- `node` version: 1.1.1
- `npm` (or `yarn`) version: npm

Relevant code or config

```javascript

```

What you did:

What happened:

Reproduction repository:

Problem description:

Feature request

Suggested solution:

autocomplete="off" does not seem to be supported. I believe it may make sense to have browser autocomplete on input field turned off as obscures the suggestions.

**Comment by darrenjennings** [comment]
It is off by default
https://github.com/Educents/vue-autosuggest/blob/master/src/Autosuggest.vue#L6

Do you mean you want ability to turn on or off?

**Comment by mhimi1** [comment]
Chrome seems to ignore autocomplete if it's not put in form tags and also Chrome admits that autocomplete="off" is not the best way to disable autofill. They recommend to give the attribute a defined value outside of the specs because, in their words, "As an example, if you have an address input field in your CRM tool that you don't want Chrome to Autofill, you can give it semantic meaning that makes sense relative to what you're asking for: e.g. autocomplete="new-user-street-address".  If Chrome encounters that, it won't try and autofill the field" (https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164). This could be isolated to chrome and thus not apply to other browsers. I should've mentioned that the issue is specific to chrome in my case. 

In chrome at least, using the suggestion the chrome team provided of providing the attribute with a value that is unknown to chrome, may still be a solution to the issue as that will most likely definitely disable the autofill in chrome.

**Comment by ranaAlkha-infotrack** [comment]
quick fix  :autocomplete="Math.random()"
