### ISSUE TITLE
Method to manually close the suggestion list?

### ISSUE THREAD

**Issue by ingvoo** [darrenjennings/vue-autosuggest#35]
- `vue-autosuggest` version: 1.3.1
- `node` version: 9.5.0
- `npm` (or `yarn`) version: 5.6.0

Thank you for this great component. I have a one question.

Problem description:
Is it possible to close the suggestion list when the user use the tab key and tabs out of the input with or without selecting an item? (From the user experience view I see it nicer to close the suggestions when it is not needed) 

I was thinking about using the `inputProps={onBlur: this.onblur}` but can not see a way to close or remove the list.

**Comment by darrenjennings** [comment]
@ingvijonasson Thanks for the note! yes, it was always possible to close the autosuggest by clearing the results. So for instance, the `:suggestions="mySuggestions"` prop could be cleared by listening to tab event. However, I have made this even easier in 1.4.1 by binding native events to the input. So you can do this now:

```vue
<vue-autosuggest 
  :suggestions="mySuggestions"
  ...
  @keydown.tab="closeSuggestions"
/>

methods: {
  closeSuggestions(e){
    console.log('tab has been pressed!', e);
    this.mySuggestions = [];
   },
```

Live demo:
https://codesandbox.io/s/vnv76pql9y

If you are stuck on previous versions you will have to do the old way of adding a listener `addListener` to the input in the `created` lifecycle method.

Closing for now.
