### ISSUE TITLE
Changing value

### ISSUE THREAD

**Issue by paulheijman** [darrenjennings/vue-autosuggest#36]
Problem description:
I would like to have the value of the input field tied to a v-model. I can set the initialValue, but some other components are changing the desired value after vue-autosuggest is loaded.

Suggested solution:
Something like exposing the `searchInput` v-model to the parent, but I'm not sure if that's the Vue way...

**Comment by darrenjennings** [comment]
Vue-autosuggest is a controlled component so it is not meant to be controlled via v-model. This should help: https://github.com/Educents/vue-autosuggest#faq

> How do I update the input programatically?

You can assign a ref to the component <vue-autosuggest ref="myRefName" ... /> and then access the input value through this.$refs.myRefName.searchInput. This is useful mainly for clearing the input. ⚠️ Note, refs are more of an "escape hatch" as they call it, so it won't trigger the onInputChange method.
