### ISSUE TITLE
Recommended way to clear input field after selection is made?

### ISSUE THREAD

**Issue by NateWr** [darrenjennings/vue-autosuggest#38]
- `vue-autosuggest` version: 1.4.1
- `node` version: 7.10.0
- `npm` (or `yarn`) version: 5.8.0

What you did:

I've built a small wrapper for the autosuggest which takes a selection and adds it to a list. When the selection is made, I'd like to clear the input field so it's ready for a new search.

I did this by overriding the `getSuggestionValue()` method to return an empty string:

```js
getSuggestionValue: function (data) {
	return '';
},
```

I'm guessing that this breaks the accessibility of the component, since using the arrow keys to move down the list no longer displays the current selection in the input box.

Is there a recommended way to clear the input field after a selection is made? Thanks!

**Comment by darrenjennings** [comment]
The answer in the FAQ might help: https://github.com/Educents/vue-autosuggest#faq

> How do I update the input programatically?

You can assign a ref to the component <vue-autosuggest ref="myRefName" ... /> and then access the
input value through this.$refs.myRefName.searchInput. This is useful mainly for clearing the input. ⚠️
Note, refs are more of an "escape hatch" as they call it, so it won't trigger the onInputChange method.

Let me know if that works for you!

**Comment by darrenjennings** [comment]
Also, I'm doing something similar in one of the storybook demos:
https://github.com/Educents/vue-autosuggest/blob/master/src/stories/index.js#L239

Demo "selecting from a list" story:
https://educents.github.io/vue-autosuggest/storybook/?selectedKind=Vue-Autosuggest&selectedStory=selecting%20from%20a%20list&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by NateWr** [comment]
:open_mouth: The one question in the FAQ! Sorry, I totally missed that.

And thanks for the link to the storybook example code. I saw the storybook but was having trouble locating the source code. Very helpful! :+1:

**Comment by Sakari369** [comment]
Hello @darrenjennings , thank you for this plugin.
I cannot seem to find a way to clear the input programmatically. I would need to clear the suggestion input to it's default value, but there is no searchInput value in the this.$refs. All I see is the originalInput. 

What would be the correct way to do this currently ? Using the latest version of vue-autosuggest. Thanks!

**Comment by darrenjennings** [comment]
@inDigiNeous latest version starting in version 2.0 uses v-model so you can clear it like any regular input in Vue

**Comment by Sakari369** [comment]
Thank you for the quick answer! That works, didn't realize this.

**Comment by morgothx** [comment]
> searchInput

Hi I'm facing the same issue and I put the ref but when I trying to "clean" the searchInput, the value keeps on my form.

I'm doing in on a clearForm function

`clearForm()
            {
                console.dir(this.$refs.suggest)
                this.form.item = null
                this.form.storage = null
                this.form.unit = null
                this.form.qty = null
                this.form.batch = null
                this.form.expiration = null
                this.$refs.suggest.searchInput = ''
                this.$refs.suggest.searchInputOriginal = ''
            },`
And printing the ref shows me that the value of searchInput and searchInputOriginal indeed changes to "" but in the form the string is still showing.

Can you please help me?

**Comment by yogithesymbian** [comment]
its broken when have 2 vue-autosuggest with one function `:get-suggestion-value="getSuggestionValue"` that assign or use by the 2 vue-autosuggest.

**Comment by Aryan3212** [comment]
Still having a few issues with clearing the search field.

**Comment by gergelykisshun** [comment]
using the "this.$refs" approach it worked for me with setting the internalValue prop to an empty string.  

 this.$refs.autosuggestRef.internalValue = '';
