### ISSUE TITLE
 Error in nextTick: "TypeError: resultsScrollElement.scrollTo is not a function"

### ISSUE THREAD

**Issue by akshay0609** [darrenjennings/vue-autosuggest#40]
getting error 
vue-autosuggest.esm.js:409 Uncaught TypeError: resultsScrollElement.scrollTo is not a function(…)

follow this example https://jsfiddle.net/darrenjennings/dugbvezs/

**Comment by darrenjennings** [comment]
@akshay0609 I have updated that fiddle with the latest v1.4.2-1. 

Can you confirm that you no longer see the error? Also, can you specify your browser/version?
https://jsfiddle.net/darrenjennings/dugbvezs/

**Comment by akshay0609** [comment]
@darrenjennings 
I am using Google Chrome, Version 54.0.2840.90 (64-bit)

you can also check on this URL https://educents.github.io/vue-autosuggest/ 
when you scrolling It's giving the error on console

**Comment by darrenjennings** [comment]
I am using babel to support older versions of browsers, only targeting latest 2 versions of Chrome. 54 does not fall into this category, but I can't seem to reproduce even with an older version

https://github.com/Educents/vue-autosuggest/blob/master/.babelrc#L7

Can you upgrade your browser and see if you still see the issue? If you do, I would suggest try to write a failing test. If we can reproduce it in the tests, then it will be easier to isolate the problem. It might be as simple as replacing scrollTo with `scroll`.

**Comment by akshay0609** [comment]
Hi @darrenjennings 
it's working on the latest Chrome version 
I checked on Chrome 66.0  version

**Comment by dominic-lear** [comment]
H @darrenjennings,

This issue is still present in IE11 Win10

**Comment by darrenjennings** [comment]
@dominic-lear thank you I will reopen this issue to get some visibility. It seems to be working on Chrome, but broken on IE11/Edge.
