### ISSUE TITLE
Integrating vee-validate attributes

### ISSUE THREAD

**Issue by hemantsinghi** [darrenjennings/vue-autosuggest#42]
- `vue-autosuggest` version: 1.4.2-1
- `node` version: 8.9.4
- `npm` (or `yarn`) version: 5.7.1

What you did:
Can we add vee-validate attributes like data-vv-as, data-vv-name to the inputProps.

Problem description:
I am developing a website, where I need the vue-autosuggest input box to be a required field and the validations should be done with vee-validate. In order to display the custom message, I need to add the vee-validate attributes.

**Comment by darrenjennings** [comment]
Have you tried adding them? Any DOM props will v-bind to input tag through input props

**Comment by hemantsinghi** [comment]
Hello, I have tried adding them and it is showing the props as it is. vee-validate is not working with it.

**Comment by hemantsinghi** [comment]
I meant that there's no way to validate the field. If we want to make it required.

**Comment by hemantsinghi** [comment]
@darrenjennings I found a way to integrate the vee-validate. 
<vue-autosuggest :suggestions="filteredOptions"
                                   :on-selected="onGolfCourseNameSelected"
                                   :limit="golfCourseShowLimit"
                                   :input-props="inputProps"
                                   v-model="golfCourseName" 
                                   data-vv-name="golfCourse" //vee-validate attributes
                                   v-validate="'required|max:100'" //vee-validate attributes>
</vue-autosuggest>

**Comment by darrenjennings** [comment]
Great, glad it works. I used vee-validate on a past project but hadn't used it with vue-autosuggest yet so good to know it works! Might add this example to the list of codesandboxes to showcase. Thanks @hemantsinghi!
