### ISSUE TITLE
Focus $refs Input

### ISSUE THREAD

**Issue by coycash** [darrenjennings/vue-autosuggest#44]
I see in the FAQ that you can change the input programmatically by using 

`this.$refs.name.searchInput`

but can't figure out a way to use focus(), ie

```
this.$refs.name.focus()
this.$refs.name.searchInput.focus()
```

**Comment by darrenjennings** [comment]
You can bind @focus directly on the component. See https://github.com/Educents/vue-autosuggest#usage under "advanced usage"

e.g. `<vue-autosuggest @focus="focusMe" .../>`

**Comment by chrispappas** [comment]
I'm not sure this answers the question - if the original question was "how do I trigger a focus event (such that the input element itself is focused and typing will occur within the input)" then I am looking for a solution for this as well.

**Comment by darrenjennings** [comment]
@chrispappas vue-autosuggest renders a normal input to the DOM so I don't think there is "vue" way of doing it. You should just focus the input like you would any normal HTML element.

e.g.

```js
// select the input any way you want and then call .focus()
document.getElementsByTagName('input')[0].focus()
```

**Comment by AndrewBogdanovTSS** [comment]
@darrenjennings this solution looks hacky. Maybe you could expose input via $refs in the next versions?

**Comment by darrenjennings** [comment]
@AndrewBogdanovTSS if you're worried about it being too hacky (since my previous comment was the entire document), I would actually recommend doing it like this:

```js
// <vue-autosuggest ref="autosuggest"
this.$refs.autosuggest.$el.querySelector("input").focus();
```

In this scenario, it is a native element method `.focus`, which I think is better left for the user to implement in lieu of vue-autosuggest handling it via prop or otherwise.

**Comment by jetlej** [comment]
This doesn't seem to work anymore. Is there a new way to programatically focus the input?

**Comment by jetlej** [comment]
Nevermind. Your examples didn't have the ref="autosuggest", so I was missing that!

**Comment by bviala** [comment]
In case it would help anyone landing on this page, here's a [codesandbox](https://codesandbox.io/s/vue-autosuggest-open-on-programmatic-focus-uvion) showing how to focus AND trigger dropdown programmatically.
