### ISSUE TITLE
searchInput type to also accept Integers

### ISSUE THREAD

**Issue by kevincobain2000** [darrenjennings/vue-autosuggest#45]
- `vue-autosuggest` version: 1.4.2-1
- `node` version:latest
- `npm` (or `yarn`) version:latest

Relevant code or config

```javascript

```

What you did:

What happened:

```
 Invalid prop: type check failed for prop "searchInput". Expected String, got Number.
```

Reproduction repository:

Problem description:

Hi, thanks for the lib. Currently, property ``searchInput`` type checks for String. This throws a vue warning when an integer is passed and selected. Is there a way to get around this warning or perhaps adding a more generic type to searchInput to accept both String and Integers.

https://github.com/Educents/vue-autosuggest/blob/master/src/parts/DefaultSection.js#L7

Suggested solution:

Allow both Integer and String

The way I am dealing with this is via converting each item inside of suggestion array to string.

```
    getSuggestions (obj, key) {
      let data = []
      for (let item of _.uniq(_.map(obj, key))) {
        data.push(String(item))
      }
      return [{data: data}]
    },
```

**Comment by darrenjennings** [comment]
Where are you overriding `searchInput`? This value is an internal property so if it is overridden it should be a string. Here is a codesandbox where I tried to reproduce your problem:
https://codesandbox.io/s/yw977zn14j

In the codesandbox `renderSuggestion` and `getInputValue` I am returning ints and I am not getting the warning so not sure why you are. If you could reproduce your usage case in codesandbox I could take a look.

**Comment by kevincobain2000** [comment]
Hi thanks for the sandbox.
Yes the searchInput is internal property and I am not overriding it all.
Steps to reproduce the warning

1. focus on input
2. select int
3. click elsewhere on dom
3. focus on input (warning)


<img width="1439" alt="screen shot 2018-07-17 at 10 02 05" src="https://user-images.githubusercontent.com/629055/42790974-b04f6a10-89a8-11e8-844e-17a76263c709.png">

**Comment by darrenjennings** [comment]
thank you for the clarification! seems like unwanted behavior. will get a patch in soon.

**Comment by vinayakkulkarni** [comment]
using v-model causes the same error now!
