### ISSUE TITLE
extend suggest

### ISSUE THREAD

**Issue by SangeCoder** [darrenjennings/vue-autosuggest#55]
like this：

![image](https://user-images.githubusercontent.com/12948798/44787709-6faaad00-abca-11e8-9df9-2500c048feb1.png)

**Comment by darrenjennings** [comment]
#52 will track issue of being able to control ability to leave results open even when clicking footer (for pagination feature) which would give ability to do this kind of thing. Closing this for now since a tabbed UI is outside of the scope of this lib.
