### ISSUE TITLE
Handle submitting when no option selected

### ISSUE THREAD

**Issue by richardwhatever** [darrenjennings/vue-autosuggest#61]
Hi,

When user enters search term that doesn't match to a suggestion, or they just haven't selected a suggestion, I want to handle the submit button. Specifically I want to redirect to search page with this search term.

At the moment it errors with: `Cannot read property 'onSelected' of undefined`.

Can you suggest a suitable approach?

Thanks!

**Comment by darrenjennings** [comment]
It depends on how you're implementing it, two different ways. 
1. If you're using the [sectionConfig](https://github.com/Educents/vue-autosuggest#sectionconfigs) to define multiple sections then you will need make sure there is a "default" section. Here is an example codepen that fires when nothing is selected: https://codesandbox.io/s/yjl79nj4zv 
i.e. the `defaultSection.onSelected()` is selected. You can replace the console.log with a window.location redirect 

2. If you do not have `sectionConfig` defined, then all on-select events will be funneled into the `on-selected` prop and you can do as you please, such as window.location.href = 'your-url-here.com'
