### ISSUE TITLE
@selected event is not firing when using vue-autosuggest in hybrid app in iOS

### ISSUE THREAD

**Issue by stripathix** [darrenjennings/vue-autosuggest#67]
I am not sure why this is happening but whenever I tap on an item to select it nothing happens. It works on the website though.

@click is firing but @selected is not firing maybe something related to ios event.

I am trying to find out why this is happening. 

Can you think of any reason why this will happen?

**Comment by stripathix** [comment]
Thanks for the tip @darrenjennings  :-). Let me try that and share my findings.

**Comment by stripathix** [comment]
This can be reproduced easily if from chrome Developer panel we select iPhone.

And then in Autosuggest.vue we comment below line because on iPhone touch devices we have to use touch events instead of mouseup as it is not firing at all. 

`document.addEventListener("mouseup", this.onDocumentMouseUp);`


I added below line in mounted() but onDocumentMouseUp function is exiting for "Clicks outside of dropdown to exit"
`document.addEventListener("touchstart", this.onDocumentMouseUp);`

<img width="1100" alt="screen shot 2018-10-11 at 2 23 05 pm" src="https://user-images.githubusercontent.com/8480351/46792528-36389600-cd61-11e8-99eb-29f2ab191436.png">

**Comment by stripathix** [comment]
To make it work I did following changes:
1) In AutoSuggest.vue

- Added following in mounted()
`document.addEventListener("touchstart", this.onDocumentMouseUp);`

- Added following in beforeDestroy()
`document.removeEventListener("touchstart", this.onDocumentMouseUp)`

2) In DefaultSection.js: Added following for event handler

```
on: {
                mouseenter: this.onMouseEnter,
                touchstart: this.onMouseEnter,
                touchend: this.onMouseLeave,
                mouseleave: this.onMouseLeave
              }
```

Now it works on iOS hybrid apps :-)

Would you like to review this change and let me know if anything not right. @darrenjennings

**Comment by darrenjennings** [comment]
@stripathix I think it sounds right if you want to [submit a pull request](https://github.com/Educents/vue-autosuggest/blob/master/CONTRIBUTING.md#contributing ) to speed things up a bit. If not I can get to it at some point in the next week.

**Comment by stripathix** [comment]
I will submit PR. Thanks.

**Comment by darrenjennings** [comment]
I unfortunately have not been able to reproduce. Thank you for your PR. If other users are experiencing same issue, we can take another look, but I'm closing for now.

**Comment by rawnly** [comment]
Hi guys, i'm having the same problem on iPhone.. (web component) anyone has solved this in other ways?

**Comment by dafergu2** [comment]
@Rawnly I just encountered this in a normal web app with iOS Safari and iOS Chrome.  I tracked it down to the fact that iOS web views don't bubble up events for nonclickable elements unless one or both of the following are true:
* The element has an `onclick=""` attribute to attach a click event handler.  An empty string is fine.
* The element has a cursor style of pointer. (Wow Apple).

My default slot had to be modified from:
```html
<div><span>Selection: {{name}}</span></div>
```
to
```html
<div onclick=""><span>Selection: {{name}}</span></div>
```

**Comment by rawnly** [comment]
Thanks @dafergu2 tomorrow I'll try and let you know!

**Comment by dafergu2** [comment]
After a little more research and testing, you can actually put the `onclick` on any ancestor element in the DOM hierarchy.  Some people even do it on the body tag of the app itself.  I chose to put it on the `<div>` of my custom component that includes the `<vue-autosuggest>` component like so:

See: https://stackoverflow.com/questions/24077725/mobile-safari-sometimes-does-not-trigger-the-click-event/24078413

My .vue file
```html
<template>
<div onclick="">
  <label class="label">Start typing ID:</label>
  <vue-autosuggest
    @input="values"
    @selected="onSelected"
    :suggestions="suggestions"
    ...>
  </vue-autosuggest>
</div>
</template>

<script lang="ts">
</script>

<style>
</style>
```

**Comment by landjonathan** [comment]
Thanks @dafergu2, `onclick=""` working well.
