### ISSUE TITLE
click item not work

### ISSUE THREAD

**Issue by EtheriousNatsu** [darrenjennings/vue-autosuggest#68]
- `vue-autosuggest` version: 1.7.1
- `node` version: 10.3.0
- `npm` (or `yarn`) version: 6.1.0

Relevant code or config

```javascript

```

What you did:
by click one item of result lists to select one.

What happened:
click not work

![image](https://user-images.githubusercontent.com/12187260/46799369-3d729a80-cd87-11e8-8b20-f741549994b3.png)

Reproduction repository:

Problem description:

Suggested solution:
can select item by click item

**Comment by darrenjennings** [comment]
1.7.1 was immediately deprecated because of this bug. Use 1.7.1-2 please and let me know if you have same issues

**Comment by EtheriousNatsu** [comment]
1.7.1-2 resolve my problem
