### ISSUE TITLE
Template or render function not defined

### ISSUE THREAD

**Issue by GELight** [darrenjennings/vue-autosuggest#76]
Hi,

We need to use your component.
Therefore I try to use the example in your readme.md.

if I open the page the follow error occurs in my browser log:

`[Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <VueAutosuggest>
       <SeachField> at src/components/SearchField.vue
         <EcomBackofficeOrderSearch> at src/pages/orders/search/App.vue
           <Root>`

This is our component:

`<template>
  <div class="searchField">
    <img src="@/assets/img/ic-magnifier.svg" alt="" />

    <vue-autosuggest
      v-if="autosuggestion"
      :suggestions="[{data:['Mario','Stefan','Danny','Patrick','Team','Deep','Thought']}]"
      :input-props="inputProps"
      @selected="onSelected"
      @click="clickHandler"
    >
      <template slot-scope="{suggestion}">
        <span class="searchField-input-suggestion-item">{{suggestion.item}}</span>
      </template>
    </vue-autosuggest>

    <input v-else v-model="searchQuery" :placeholder="placeholderValue()" class="searchField-input" v-on:keyup.enter="submitSearch" />

    <img src="@/assets/img/ic-x.svg" alt="" @click="clear" v-if="isValue()" class="searchField-clear" />
  </div>
</template>

<script>
import axios from 'axios'
import config from '../config/config'
import VueAutosuggest from 'vue-autosuggest'

export default {
  name: 'SeachField',
  components: {
    VueAutosuggest
  },
  props: {
    value: String,
    placeholder: String,
    autosuggestion: String
  },
  data () {
    return {
      searchQuery: this.value,
      searchResult: null,
      errors: [],
      inputProps: {
        id: 'searchField-input',
        onInputChange: this.fetchResults,
        placeholder: this.placeholderValue(),
        class: 'searchField-input'
      },
      suggestions: []
    }
  },
  methods: {
    placeholderValue () {
      if (this.placeholder) {
        return this.placeholder
      }

      return this.$i18n.t('search.input.placeholder')
    },

    clear () {
      this.searchQuery = ''
    },

    isValue () {
      if (!this.searchQuery) {
        return false
      }

      return true
    },

    submitSearch () {
      if (this.searchQuery) {
        let restApiPath = config.restApiPath.replace('{searchQuery}', this.searchQuery)

        axios.get(restApiPath)
          .then(response => {
            this.searchResult = response.data
          })
          .catch(e => {
            this.errors.push(e)
          })
      }
    },

    onInputChange (item, oldItem) {
      console.log(item, oldItem)
    },

    onSelected (selectedItem) {
      console.log(selectedItem)
    },

    clickHandler (event) {
      console.log(event)
    },

    fetchResults () {
      console.log('fetch...')
    }

  }
}
</script>

<style scoped lang="scss">
  @import "~ecom-backoffice-styles/dist/index.scss";
  @import "~ecom-backoffice-styles/dist/mixins/mixins.scss";

  .searchField {
    background: $white;
    border: 1px solid $medium-gray;
    border-radius: 2px;
    height: 40px;
    display: flex;
    justify-content: space-between;
    padding: 0 $space-default / 2;
    width: 30em;

    > * ~ * {
      margin-left: $space-default / 2;
    }

    .searchField-input {
      border: 0;
      display: flex;
      justify-self: stretch;
      flex-grow: 2;
      width: 30em;

      @include text(
        $font-size: 16px,
        $color: $dark-gray
      );

      @include input-placeholder {
        color: $regular-gray;
      }

      &:active,
      &:focus {
        border: 0;
        outline: none;
      }
    }

    .searchField-clear {

      &:hover {
        cursor: pointer;
      }

    }

  }

</style>
`

What is needed to be added in our component?
Thanks for help

Best regards,
Mario

PS: I sorry for this wrong code formatting. I do not know, how I can add my single component better hier in guthub.

**Comment by darrenjennings** [comment]
The error had a typo in `<searchfield>`. If you change it from `<SeachField>`. I think the real issue is you need to fix the import statement. Check out the readme to see how you do it locally inside a component. The way you're doing it is importing it as a plugin. Hope that helps.

**Comment by GELight** [comment]
Yes ... you are right. This was the problem.
Many thanks for this tip. 

It works now. :+1: :)
