### ISSUE TITLE
Focus on the first item in the list

### ISSUE THREAD

**Issue by lordenas** [darrenjennings/vue-autosuggest#77]
Hi. Thank You for Your work. Is it possible to make the first item of the list always active. For example: full name "Lynne Graham". I write " Lean."... press enter and select the first.

![ice_video_20181106-160812](https://user-images.githubusercontent.com/15974195/48066713-639d2600-e1df-11e8-8f3c-b6166ea13da9.gif)

**Comment by darrenjennings** [comment]
You can do it by accessing the internal method `setCurrentIndex` via refs:

https://mq9869lz2x.codesandbox.io/

e.g. 
```js 
this.$refs.autosuggest.setCurrentIndex(0)
```

**disclaimer**: refs are more of an escape hatch so it will work for now but I plan on making this part of of the api in the future where you can hook into the event system with a "data reducer". So the method setCurrentIndex is subject to change in future releases. Should be good for now 🙃

**Comment by lordenas** [comment]
Thank you!

**Comment by jetlej** [comment]
This doesn't seem to work anymore. Is there an updated version?

**Comment by jetlej** [comment]
Or rather, could you make the source code visible on your codesandbox link? (https://mq9869lz2x.codesandbox.io/)
