### ISSUE TITLE
IE11/EDGE js errors on scrolling & selecting item in list via keys 

### ISSUE THREAD

**Issue by dz000** [darrenjennings/vue-autosuggest#80]
- `vue-autosuggest` version: 1.7.3
- `node` version: 8.12.0
- `npm` (or `yarn`) version: 6.4.1

Added vue-autosuggest to nuxt project.

What happened:
Scrolling on key down/up & selecting item via enter key doesn't work properly in IE11 & EDGE
Scrolling on key down/up throws errors if scrolling a list with items hidden in overflow:
Error Message: Object doesn't support property or method scrollTo

Reproduction repository:
Storybook of vue-autosuggest:
https://educents.github.io/vue-autosuggest/storybook/

Problem description:
Maybe: https://stackoverflow.com/questions/51517324/scrollto-method-doesnt-work-in-edge

Suggested solution:
Can you have a look at the problem? 
Was it the intention to support internet explorer?

Thank you!

**Comment by scottadamsmith** [comment]
I had to use two polyfills for IE.

Object.assign(): There is one  directly in the documentation here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

For scrollTo, I had to add to add the smooth scroll-polyfill library: https://github.com/iamdustan/smoothscroll

**Comment by dz000** [comment]
@scottadamsmith  Thanks again - everything works now! IE11 & EDGE
