### ISSUE TITLE
Internal state is not correctly cleared

### ISSUE THREAD

**Issue by marchbnr** [darrenjennings/vue-autosuggest#82]
- `vue-autosuggest` version: 1.7.3
- `node` version: v10.5.0
- `npm` (or `yarn`) version: npm 6.5.0

Problem description:
Clearing the search input as suggested in the FAQ does not correctly reset the internal state.

What you did:
Cleared the search input like this: this.$refs.myRefName.searchInput = ""

What happened:
The internal state is not cleared. Hitting enter will trigger the selection handler with the same item again althoug the search text is empty.

How to reproduce:
It can be reproduced in [this](https://educents.github.io/vue-autosuggest/storybook/?selectedKind=Vue-Autosuggest&selectedStory=selecting%20from%20a%20list) storybook. Just select one of the options and then press enter when the search field is empty. It will add the same element again.

**Comment by darrenjennings** [comment]
@marchbnr Ah yes I see what you mean. This was the kinda "gotcha" that comes with $refs, but glad it's revealing the downsides. Was playing around with the storybook and it looks like I am able to replicate the behavior pretty easily though this demo is a bit better as it handles uniqueness of the list https://codesandbox.io/s/6246p5r063 Will mark this as a bug, and will try and get to it, but PRs welcome!
