### ISSUE TITLE
Suggestions list is not properly closing

### ISSUE THREAD

**Issue by artem-tim** [darrenjennings/vue-autosuggest#87]
The issue is reproducible on your demo page https://darrenjennings.github.io/vue-autosuggest/
Clicking outside of the list does not always close the list, depending on the click position. Towards the right side of the screen, clicks won't close the list, but left side clicks will.
With Chrome on Linux Version 69.0.3497.92 (Official Build) (64-bit)

**Comment by darrenjennings** [comment]
thanks @artem-tim I think the issue might be in here somewhere if you wanted to debug further. I will take a look a little later thanks for the issue.

https://github.com/darrenjennings/vue-autosuggest/blob/5540349858f40688082bf27b3f5f79ae316e9589/src/Autosuggest.vue#L452
