### ISSUE TITLE
[feature request] make the `autosuggest__` CSS prefix configurable

### ISSUE THREAD

**Issue by wujekbogdan** [darrenjennings/vue-autosuggest#97]
All CSS classes have a `autosuggest__` prefix. Could you make this prefix configurable via props?

**Comment by darrenjennings** [comment]
Didn't get this in for [2.0.0](https://github.com/darrenjennings/vue-autosuggest/releases/tag/v2.0.0), but can implement it without a breaking change. Help still wanted.
